### ISSUE TITLE
Multiple selectboxes support

### ISSUE THREAD

**Issue by jenstornell** [zoltantothcom/vanilla-js-dropdown#11]
Overall this works really well. =) Anyway, I use 2 selectboxes and I have restyled them a bit, like below.

![image](https://user-images.githubusercontent.com/927011/47156041-7a3e1480-d2e6-11e8-8fbe-df560e03e327.png)

In my JS I have this:

```js
var select = new CustomSelect({
    elem: "banks",
});

var select2 = new CustomSelect({
    elem: "age",
});
```

While it works, I think it would be much better to add a `selector` param instead. Then multiple selects could be added in one go.

**Example**

```js
var select = new CustomSelect({
    selector: "#banks, #age",
});
```

...or even...

```js
var select = new CustomSelect({
    selector: "select",
});
```

**Comment by zoltantothcom** [comment]
I did a proof of concept version on [JSBin](https://jsbin.com/lojevikusa/7/edit?js,console,output)

It works with a passed in list of _id_-s or a list of DOM elements. However you can't easily use anymore the available methods, e.g. `.open()` or `.toggle()`. Sure you can create an array of selects and do:
```
selects[1].open()
```
This is exactly what I did in the demo above. But what if the order of selects changes? Or a select gets inserted dynamically? What if you calling several methods on different selects? All the pieces have to be updated, which is very error prone.

You can try to come up with a naming convention for generated dropdowns, but that requires the developers to keep in mind how exactly they are being named or check the manual every time.

Being said, the ability to have multiple selectors introduces a lot of usage complexity and potentially increases the size as well, so the benefits are highly questionable. 

Sure, having 
```
var select1 = new CustomSelect({ elem: "banks, age" });
```
instead of
```
var select1 = new CustomSelect({ elem: "banks" });
var select2 = new CustomSelect({ elem: "age" });
```
looks neater and makes your code a line shorter, but can't justify the increased complexity.
